import 'package:flutter/material.dart';

class TechnicalLocalization {
  static const Map<String, Map<String, String>> _data = {
    'en': {
      'system_settings': 'CORE SYSTEM SETTINGS',
      'configure_env': 'Configure your operating environment',
      'select_language': 'SELECT LANGUAGE',
      'automatic': 'Automatic',
      'continue': 'CONTINUE',
      'welcome_back': 'WELCOME BACK',
      'enter_credentials': 'Enter your credentials',
      'email': 'Email',
      'password': 'Password',
      'login': 'LOGIN',
      'sign_up': 'SIGN UP',
      'confirm_password': 'Confirm Password',
      'dont_have_account': 'Don\'t have an account? Sign Up',
      'stats': 'SYSTEM STATS',
      'saga': 'DAILY SAGA',
      'quests': 'ACTIVE QUESTS',
      'future': 'IMMINENT FUTURE',
      'progress': 'EVOLUTION PROGRESS',
      'level': 'LEVEL',
      'phase': 'PHASE',
      'genesis': 'GENESIS',
      'xp': 'EXPERIENCE POINTS',
      'discipline': 'DISCIPLINE',
      'health': 'HEALTH',
      'wealth': 'WEALTH',
      'focus': 'FOCUS',
      'booting': 'Booting Life.OS...',
      'intro_title': 'What is Life.OS?',
      'intro_desc': 'Transform your daily life into a real RPG experience.',
      'hello_hero': 'Hello, Hero',
      'user_name': 'Omar Fathi',
      'level_short': 'LVL 1',
      'xp_progress': 'XP PROGRESS',
      'phase_genesis': 'PHASE: GENESIS',
      'days_left_30': '30 DAYS LEFT',
      'today_story_chapter': 'TODAY\'S STORY CHAPTER',
      'daily_quests': 'DAILY QUESTS',
      'future_30_days': 'YOUR FUTURE IN 30 DAYS',
      'simulate': 'SIMULATE',
      'home': 'Home',
      'quests_nav': 'Quests',
      'saga_nav': 'Saga',
      'future_nav': 'Future',
      'profile': 'Profile',
      'quest_complete_profile': 'Complete your profile',
      'quest_define_goals': 'Define your goals',
      'quest_start_first': 'Start your first quest',
      'saga_placeholder': '"Your story hasn\'t started yet... Complete quests to write the first chapter of your saga."',
      'welcome_back_title': 'Welcome Back',
      'life_waiting': 'Life.OS is waiting for you',
      'forgot_password': 'Forgot Password?',
      'or': 'OR',
      'continue_google': 'Continue with Google',
      'register_prompt': 'Don\'t have an account? Register now',
      'enter_email_first': 'Please enter your email first',
      'reset_link_sent': 'Reset link sent to your email',
      'join_system': 'Join the System',
      'start_story': 'Start writing your story now',
      'full_name': 'Full Name',
      'create_account': 'Create Account',
      'already_have_account': 'Already have an account? Login',
      'onboarding_title_1': 'What is Life.OS?',
      'onboarding_desc_1': 'Transform your daily life into a real RPG experience. Log your day, earn XP, and level up.',
      'onboarding_title_2': 'The Saga',
      'onboarding_desc_2': 'Every day AI writes a chapter of your life novel. You are the hero.',
      'onboarding_title_3': 'See your future',
      'onboarding_desc_3': 'Smart simulation that shows you where you will be in 30 days. Change your habits, change your path.',
      'start_journey': 'Start Journey',
      'next': 'Next',
      'skip': 'Skip',
      'ok': 'OK',
      'tutorial_evolution_title': 'Evolution Progress',
      'tutorial_evolution_desc': 'Monitor your journey to the next level.',
      'tutorial_metrics_title': 'Core Metrics',
      'tutorial_metrics_desc': 'Your standing in Health, Wealth, and Focus.',
      'tutorial_saga_title': 'Daily Saga',
      'tutorial_saga_desc': 'Your AI-generated life narrative lives here.',
      'tutorial_quests_title': 'Active Quests',
      'tutorial_quests_desc': 'Complete these to earn XP and level up.',
      'future_detail_desc': 'The System currently lacks sufficient data to model your future. Begin improving your stats to enable simulation.',
      'experience_detail_desc': 'Complete daily quests, stick to your schedule, and log your actions to gain Experience. Each level unlocks new system capabilities.',
      'xp_current_default': '0 / 1,000 XP',
      'reward_50_xp': '+50 XP',
      'reward_30_xp': '+30 XP',
      'reward_20_xp': '+20 XP',
      'future_stats_preview': 'Discipline 89% • Health 92% • Focus 84%',
      'login_email_placeholder': 'omar@example.com',
      'register_email_placeholder': 'example@lifeos.com',
    },
    'ar': {
      'system_settings': 'إعدادات النظام الأساسية',
      'configure_env': 'تهيئة بيئة التشغيل الخاصة بك',
      'select_language': 'اختر اللغة',
      'automatic': 'تلقائي',
      'continue': 'متابعة',
      'welcome_back': 'أهلاً بعودتك',
      'enter_credentials': 'أدخل بيانات الاعتماد الخاصة بك',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'login': 'تسجيل الدخول',
      'sign_up': 'إنشاء حساب',
      'confirm_password': 'تأكيد كلمة المرور',
      'dont_have_account': 'ليس لديك حساب؟ سجل الآن',
      'stats': 'إحصائيات النظام',
      'saga': 'الرواية اليومية',
      'quests': 'المهام نشطة',
      'future': 'المستقبل الوشيك',
      'progress': 'تقدم التطور',
      'level': 'المستوى',
      'phase': 'المرحلة',
      'genesis': 'البداية',
      'xp': 'نقاط الخبرة',
      'discipline': 'الانضباط',
      'health': 'الصحة',
      'wealth': 'الثروة',
      'focus': 'التركيز',
      'booting': 'بدء تشغيل Life.OS...',
      'intro_title': 'ما هو Life.OS؟',
      'intro_desc': 'حول حياتك اليومية إلى تجربة RPG حقيقية.',
      'hello_hero': 'مرحباً، أيها البطل',
      'user_name': 'عمر فتحي',
      'level_short': 'مستوى ١',
      'xp_progress': 'التقدم في الخبرة',
      'phase_genesis': 'المرحلة: البداية',
      'days_left_30': '٣٠ يوم متبقي',
      'today_story_chapter': 'فصل اليوم من الرواية',
      'daily_quests': 'المهام اليومية',
      'future_30_days': 'مستقبلك بعد 30 يوماً',
      'simulate': 'افتح المحاكاة',
      'home': 'الرئيسية',
      'quests_nav': 'المهام',
      'saga_nav': 'القصة',
      'future_nav': 'المستقبل',
      'profile': 'الملف',
      'quest_complete_profile': 'أكمل ملفك الشخصي',
      'quest_define_goals': 'حدد أهدافك',
      'quest_start_first': 'ابدأ أول مهمة',
      'saga_placeholder': '"لم تبدأ قصتك بعد... أكمل المهام لتكتب الفصل الأول من روايتك."',
      'welcome_back_title': 'مرحباً مجدداً',
      'life_waiting': 'Life.OS ينتظرك',
      'forgot_password': 'نسيت كلمة المرور؟',
      'or': 'أو',
      'continue_google': 'متابعة مع Google',
      'register_prompt': 'ليس لديك حساب؟ سجل الآن',
      'enter_email_first': 'ادخل بريدك الإلكتروني أولاً',
      'reset_link_sent': 'تم إرسال رابط إعادة التعيين لبريدك',
      'join_system': 'انضم إلى الـ System',
      'start_story': 'ابدأ كتابة قصتك الآن',
      'full_name': 'الاسم الكامل',
      'create_account': 'إنشاء حساب',
      'already_have_account': 'هل لديك حساب بالفعل؟ سجل الدخول الآن',
      'onboarding_title_1': 'ما هو Life.OS؟',
      'onboarding_desc_1': 'حوّل حياتك اليومية إلى تجربة RPG حقيقية. سجّل يومك واكسب XP وارتقِ.',
      'onboarding_title_2': 'The Saga',
      'onboarding_desc_2': 'كل يوم يكتب الذكاء الاصطناعي فصلاً من رواية حياتك. أنت البطل.',
      'onboarding_title_3': 'شوف مستقبلك',
      'onboarding_desc_3': 'محاكاة ذكية تُريك أين ستكون بعد 30 يوماً. غيّر عاداتك وغيّر مسارك.',
      'start_journey': 'ابدأ رحلتك',
      'next': 'التالي',
      'skip': 'تخطي',
      'ok': 'موافق',
      'tutorial_evolution_title': 'تقدم التطور',
      'tutorial_evolution_desc': 'راقب مسار رحلتك للمستوى التالي.',
      'tutorial_metrics_title': 'مقاييسك الأساسية',
      'tutorial_metrics_desc': 'مكانتك في الصحة والثروة والتركيز.',
      'tutorial_saga_title': 'روايتك اليومية',
      'tutorial_saga_desc': 'هنا تسكن رواية حياتك التي يكتبها الذكاء الاصطناعي.',
      'tutorial_quests_title': 'المهام النشطة',
      'tutorial_quests_desc': 'أكمل هذه المهام لكسب الخبرة ورفع مستواك.',
      'future_detail_desc': 'النظام يفتقر حالياً إلى البيانات الكافية لنمذجة مستقبلك. ابدأ في تحسين إحصائياتك لتمكين المحاكاة.',
      'experience_detail_desc': 'أكمل المهام اليومية، التزم بجدولك، وقم بتسجيل أفعالك لزيادة خبرتك. كل مستوى يفتح قدرات جديدة في النظام.',
      'xp_current_default': '0 / 1,000 XP',
      'reward_50_xp': '+50 XP',
      'reward_30_xp': '+30 XP',
      'reward_20_xp': '+20 XP',
      'future_stats_preview': 'الانضباط 89% • الصحة 92% • التركيز 84%',
      'login_email_placeholder': 'omar@example.com',
      'register_email_placeholder': 'example@lifeos.com',
    },
    'es': {
      'system_settings': 'AJUSTES DEL SISTEMA',
      'configure_env': 'Configure su entorno operativo',
      'select_language': 'SELECCIONAR IDIOMA',
      'automatic': 'Automático',
      'continue': 'CONTINUAR',
      'welcome_back': 'BIENVENIDO',
      'enter_credentials': 'Ingrese sus credenciales',
      'email': 'Correo electrónico',
      'password': 'Contraseña',
      'login': 'ACCEDER',
      'sign_up': 'REGISTRARSE',
      'confirm_password': 'Confirmar contraseña',
      'dont_have_account': '¿No tienes cuenta? Regístrate',
      'already_have_account': '¿Ya tienes cuenta? Acceder',
      'stats': 'ESTADÍSTICAS',
      'saga': 'SAGA DIARIA',
      'quests': 'MISIONES ACTIVAS',
      'future': 'FUTURO INMINENTE',
      'progress': 'PROGRESO',
      'level': 'NIVEL',
      'phase': 'FASE',
      'genesis': 'GÉNESIS',
      'xp': 'PUNTOS DE EXPERIENCIA',
      'discipline': 'DISCIPLINA',
      'health': 'SALUD',
      'wealth': 'RIQUEZA',
      'focus': 'ENFOQUE',
      'booting': 'Iniciando Life.OS...',
      'intro_title': '¿Qué es Life.OS?',
      'intro_desc': 'Transforma tu vida en una experiencia RPG real.',
    },
    'fr': {
      'system_settings': 'PARAMÈTRES SYSTÈME',
      'configure_env': 'Configurez votre environnement',
      'select_language': 'CHOISIR LA LANGUE',
      'automatic': 'Automatique',
      'continue': 'CONTINUER',
      'welcome_back': 'BON RETOUR',
      'enter_credentials': 'Entrez vos identifiants',
      'email': 'Email',
      'password': 'Mot de passe',
      'login': 'CONNEXION',
      'sign_up': 'S\'INSCRIRE',
      'confirm_password': 'Confirmer le mot de passe',
      'dont_have_account': 'Pas de compte? S\'inscrire',
      'already_have_account': 'Déjà un compte? Connexion',
      'stats': 'STATISTIQUES',
      'saga': 'SAGA QUOTIDIENNE',
      'quests': 'QUÊTES ACTIVES',
      'future': 'FUTUR IMMINENT',
      'progress': 'ÉVOLUTION',
      'level': 'NIVEAU',
      'phase': 'PHASE',
      'genesis': 'GENÈSE',
      'xp': 'POINTS D\'EXPÉRIENCE',
      'discipline': 'DISCIPLINE',
      'health': 'SANTÉ',
      'wealth': 'RICHESSE',
      'focus': 'FOCUS',
      'booting': 'Démarrage de Life.OS...',
      'intro_title': 'C\'est quoi Life.OS?',
      'intro_desc': 'Transformez votre vie en un véritable RPG.',
    },
    'de': {
      'system_settings': 'SYSTEMEINSTELLUNGEN',
      'configure_env': 'Konfigurieren Sie Ihr System',
      'select_language': 'SPRACHE WÄHLEN',
      'automatic': 'Automatisch',
      'continue': 'WEITER',
      'welcome_back': 'WILLKOMMEN ZURÜCK',
      'enter_credentials': 'Anmeldedaten eingeben',
      'email': 'E-Mail',
      'password': 'Passwort',
      'login': 'LOGIN',
      'sign_up': 'REGISTRIEREN',
      'confirm_password': 'Passwort bestätigen',
      'dont_have_account': 'Kein Konto? Registrieren',
      'already_have_account': 'Konto vorhanden? Login',
      'stats': 'SYSTEMSTATISTIK',
      'saga': 'TÄGLICHE SAGA',
      'quests': 'AKTIVE QUESTS',
      'future': 'ZUKUNFT',
      'progress': 'ENTWICKLUNG',
      'level': 'LEVEL',
      'phase': 'PHASE',
      'genesis': 'GENESIS',
      'xp': 'ERFAHRUNGSPUNKTE',
      'discipline': 'DISZIPLIN',
      'health': 'GESUNDHEIT',
      'wealth': 'WOHLSTAND',
      'focus': 'FOKUS',
      'booting': 'Life.OS startet...',
      'intro_title': 'Was ist Life.OS?',
      'intro_desc': 'Verwandeln Sie Ihr Leben in ein echtes RPG.',
    },
    'pt': {
      'system_settings': 'CONFIGURAÇÕES',
      'configure_env': 'Configure seu ambiente',
      'select_language': 'SELECIONAR IDIOMA',
      'automatic': 'Automático',
      'continue': 'CONTINUAR',
      'welcome_back': 'BEM-VINDO',
      'enter_credentials': 'Insira suas credenciais',
      'email': 'E-mail',
      'password': 'Senha',
      'login': 'ENTRAR',
      'sign_up': 'CADASTRAR',
      'confirm_password': 'Confirmar senha',
      'dont_have_account': 'Não tem conta? Cadastre-se',
      'already_have_account': 'Já tem conta? Entrar',
      'stats': 'ESTATÍSTICAS',
      'saga': 'SAGA DIÁRIA',
      'quests': 'MISSÕES ATIVAS',
      'future': 'FUTURO IMINENTE',
      'progress': 'EVOLUÇÃO',
      'level': 'NÍVEL',
      'phase': 'FASE',
      'genesis': 'GÊNESIS',
      'xp': 'PONTOS DE EXPERIÊNCIA',
      'discipline': 'DISCIPLINA',
      'health': 'SAÚDE',
      'wealth': 'RIQUEZA',
      'focus': 'FOCO',
      'booting': 'Iniciando Life.OS...',
      'intro_title': 'O que é Life.OS?',
      'intro_desc': 'Transforme seu dia a dia em um RPG real.',
    },
    'ru': {
      'system_settings': 'НАСТРОЙКИ СИСТЕМЫ',
      'configure_env': 'Настройте рабочую среду',
      'select_language': 'ВЫБОР ЯЗЫКА',
      'automatic': 'Автоматически',
      'continue': 'ПРОДОЛЖИТЬ',
      'welcome_back': 'С ВОЗВРАЩЕНИЕМ',
      'enter_credentials': 'Введите свои данные',
      'email': 'Email',
      'password': 'Пароль',
      'login': 'ВОЙТИ',
      'sign_up': 'РЕГИСТРАЦИЯ',
      'confirm_password': 'Подтвердите пароль',
      'dont_have_account': 'Нет аккаунта? Регистрация',
      'already_have_account': 'Есть аккаунт? Войти',
      'stats': 'СТАТИСТИКА',
      'saga': 'ДНЕВНАЯ САГА',
      'quests': 'АКТИВНЫЕ КВЕСТЫ',
      'future': 'БУДУЩЕЕ',
      'progress': 'ЭВОЛЮЦИЯ',
      'level': 'УРОВЕНЬ',
      'phase': 'ФАЗА',
      'genesis': 'ГЕНЕЗИС',
      'xp': 'ОЧКИ ОПЫТА',
      'discipline': 'ДИСЦИПЛИНА',
      'health': 'ЗДОРОВЬЕ',
      'wealth': 'БОГАТСТВО',
      'focus': 'ФОКУС',
      'booting': 'Загрузка Life.OS...',
      'intro_title': 'Что такое Life.OS?',
      'intro_desc': 'Превратите свою жизнь в настоящее RPG.',
    },
    'ja': {
      'system_settings': 'システム設定',
      'configure_env': '動作環境を構成する',
      'select_language': '言語を選択',
      'automatic': '自動',
      'continue': '続行',
      'welcome_back': 'おかえりなさい',
      'enter_credentials': '資格情報を入力してください',
      'email': 'メールアドレス',
      'password': 'パスワード',
      'login': 'ログイン',
      'sign_up': '新規登録',
      'confirm_password': 'パスワードを再入力',
      'dont_have_account': 'アカウントをお持ちでないですか？新規登録',
      'already_have_account': 'アカウントをお持ちですか？ログイン',
      'stats': 'システム統計',
      'saga': 'デイリーサが',
      'quests': 'アクティブクエスト',
      'future': '差し迫った未来',
      'progress': '進化プロセス',
      'level': 'レベル',
      'phase': 'フェーズ',
      'genesis': '創世記',
      'xp': '経験値',
      'discipline': '規律',
      'health': '健康',
      'wealth': '富',
      'focus': '集中',
      'booting': 'Life.OSを起動中...',
      'intro_title': 'Life.OSとは？',
      'intro_desc': '日常生活を本物のRPG体験に変える。',
    },
    'zh': {
      'system_settings': '核心系统设置',
      'configure_env': '配置您的运行环境',
      'select_language': '选择语言',
      'automatic': '自动',
      'continue': '继续',
      'welcome_back': '欢迎回来',
      'enter_credentials': '输入您的凭据',
      'email': '电子邮件',
      'password': '密码',
      'login': '登录',
      'sign_up': '注册',
      'confirm_password': '确认密码',
      'dont_have_account': '还没有账号？现在注册',
      'already_have_account': '已有账号？登录',
      'stats': '系统统计',
      'saga': '每日传奇',
      'quests': '当前任务',
      'future': '未来模拟',
      'progress': '进化进度',
      'level': '等级',
      'phase': '阶段',
      'genesis': '创世',
      'xp': '经验值',
      'discipline': '自律',
      'health': '健康',
      'wealth': '财富',
      'focus': '专注',
      'booting': 'Life.OS 正在启动...',
      'intro_title': '什么是 Life.OS？',
      'intro_desc': '将您的日常生活转化为真实的RPG体验。',
    },
    'hi': {
      'system_settings': 'कोर सिस्टम सेटिंग्स',
      'configure_env': 'अपना ऑपरेटिंग वातावरण कॉन्फ़िगर करें',
      'select_language': 'भाषा चुनें',
      'automatic': 'स्वचालित',
      'continue': 'जारी रखें',
      'welcome_back': 'स्वागत है',
      'enter_credentials': 'अपनी साख दर्ज करें',
      'email': 'ईमेल',
      'password': 'पासवर्ड',
      'login': 'लॉगिन',
      'sign_up': 'साइन अप करें',
      'confirm_password': 'पासवर्ड की पुष्टि करें',
      'dont_have_account': 'खाता नहीं है? साइन अप करें',
      'already_have_account': 'पहले से ही खाता है? लॉगिन',
      'stats': 'सिस्टम आंकड़े',
      'saga': 'दैनिक सागा',
      'quests': 'सक्रिय खोज',
      'future': 'निकट भविष्य',
      'progress': 'विकास प्रगति',
      'level': 'स्तर',
      'phase': 'चरण',
      'genesis': 'जेनेसिस',
      'xp': 'अनुभव अंक',
      'discipline': 'अनुशासन',
      'health': 'स्वास्थ्य',
      'wealth': 'धन',
      'focus': 'फोकस',
      'booting': 'Life.OS बूट हो रहा है...',
      'intro_title': 'Life.OS क्या है?',
      'intro_desc': 'अपने दैनिक जीवन को वास्तविक RPG अनुभव में बदलें।',
    },
  };

  static String translate(BuildContext context, String key) {
    // Basic fallback logic
    final locale = Localizations.localeOf(context).languageCode;
    return _data[locale]?[key] ?? _data['en']![key]!;
  }
}
